```js {cmd=node}
//第一种
promise.then((res) => {
    console.log('then:', res);
}).catch((err) => {
    console.log('catch:', err);
})
//第二种
promise.then((res) => {
    console.log('then:', res);
}, (err) => {
    console.log('catch:', err);
})

// 第一种 catch 方法可以捕获到 catch 之前整条 promise 链路上所有抛出的异常。
// 第二种 then 方法的第二个参数捕获的异常依赖于上一个 promise 对象的执行结果。
```